<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="style.css" rel="stylesheet">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <title>Document</title>
</head>
<body>
<section class="newsletter">
<div class="container">
<div class="row">
<div class="col-sm-12">
	<div class="content">
		<h2>SUBSCRIBE TO OUR NEWSLETTER</h2>
        <form method="post" action="newsletter.php">  
	<div class="input-group">
         <input type="text" name="email" id="email" class="form-control" placeholder="Enter your email">
         <span class="input-group-btn" >  
         <button class="btn" type="submit">Subscribe Now</button>
         </span>
          </div>
    
        <p> <?php if (!empty($valid)){
           echo $valid;
       } 
       ?>
       </p>
       <p> <?php if (!empty($error)){
           echo $error;
       }
        ?>
       </p> 
	</div>
    </form>
</div>
</div>
</div>
</section>
</body>
</html>